# Generated by Django 4.0.1 on 2022-01-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('especie', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('rutPropietario', models.CharField(max_length=9)),
                ('telefonoContacto', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=50)),
                ('nota', models.CharField(max_length=100)),
            ],
        ),
    ]
