# Generated by Django 4.0.1 on 2022-01-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscaTuMascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='estaPerdido',
            field=models.BooleanField(default=False),
        ),
    ]
