# Generated by Django 4.0.1 on 2022-02-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscaTuMascota', '0003_alter_mascota_rutpropietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='nota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
