# Generated by Django 4.0.1 on 2022-02-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscaTuMascota', '0004_alter_mascota_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='qr',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
